MIXED Errors_number BY Run Instruction 
  /CRITERIA=DFMETHOD(SATTERTHWAITE) CIN(95) MXITER(100) MXSTEP(10) SCORING(1) 
    SINGULAR(0.000000000001) HCONVERGE(0, ABSOLUTE) LCONVERGE(0, ABSOLUTE) PCONVERGE(0.000001, ABSOLUTE) 
  /FIXED= Run Instruction | SSTYPE(3) 
  /METHOD=ML 
  /PRINT=DESCRIPTIVES  SOLUTION 
  /RANDOM=INTERCEPT | SUBJECT(Participant) COVTYPE(ID) 
  /EMMEANS=TABLES(Run) COMPARE ADJ(BONFERRONI) 
  /EMMEANS=TABLES(Instruction) COMPARE ADJ(BONFERRONI) .
